# Generated by Django 5.1.9 on 2025-06-28 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
        ("projects", "0031_add_evaluation_field_config"),
        ("tasks", "0056_add_prediction_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "updated_at"], name="task_project_64438a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "created_at"], name="task_project_a6de34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "total_annotations"], name="task_project_69db22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "is_labeled", "id"], name="task_project_07d938_idx"
            ),
        ),
    ]
