# Generated by Django 5.1.9 on 2025-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0057_task_task_project_64438a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="field_annotations",
            field=models.JSONField(
                default=dict,
                help_text="Field-level annotations and comments for form fields",
                null=True,
                verbose_name="field annotations",
            ),
        ),
    ]
