# Generated by Django 5.1.9 on 2025-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0058_add_field_annotations_to_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationdraft",
            name="field_annotations",
            field=models.JSONField(
                default=dict,
                help_text="Field-level annotations and comments for form fields",
                null=True,
                verbose_name="field annotations",
            ),
        ),
    ]
