title: Invoice Recognition
type: community
group: Document AI
image: /static/templates/optical-character-recognition.png
details: <h1>Write down the JSON text of the document</h1>
config: |
  <ResizableView leftMinWidth="300" rightMinWidth="250" rightInitialWidth="410">
    <!-- 左侧：文档渲染区 -->
    <View>
      <!-- 用内嵌 HTML 渲染 PDF / 图片，也可换成 <Image> / <PDF> -->
      <HyperText name="pdf" value="$pdf" inline="true" height="100%"/>
    </View>
    <!-- 右侧：字段校对区 -->
    <View style="flex: 30%;padding-left: 1em; border-left: 1px solid #ddd;">
      <Text name="filename_display" value="$filename" /> 
        <TextArea
          name="invoices_json"
          value="$invoices_json"
          toName="pdf"
          rows="36"
          displayMode="tag"
          showSubmitButton="false"
        />
      <Text name="comment_display" value="备注" /> 
        <TextArea
          name="comment"
          toName="pdf"
          rows="1"
          displayMode="tag"
          showSubmitButton="false"
        />
    </View>
  </ResizableView>
