# Generated by Django 5.1.9 on 2025-06-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_alter_labelstreamhistory_id_alter_project_id_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this project belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="workspaces.workspace",
            ),
        ),
    ]
