# Generated by Django 5.1.9 on 2025-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_add_evaluation_field_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimport",
            name="merge_strategy",
            field=models.CharField(
                default="create_new",
                help_text="Strategy for handling existing tasks: create_new, merge",
                max_length=64,
            ),
        ),
    ]
