# Generated by Django 5.1.9 on 2025-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="name",
            field=models.CharField(
                help_text="Name of the prompt", max_length=255, unique=True
            ),
        ),
    ]
