# Generated by Django 5.1.9 on 2025-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_alter_prompt_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="description",
        ),
    ]
