# Generated by Django 5.1.9 on 2025-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_remove_prompt_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="response_schema",
            field=models.JSONField(
                blank=True,
                help_text="JSON schema for structured AI model response format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Temperature for AI model response (0.0-2.0). Controls randomness: lower is more deterministic.",
                null=True,
            ),
        ),
    ]
