# Generated by Django 5.1.9 on 2025-08-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0004_prompt_response_schema_prompt_temperature"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this prompt belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="workspaces.workspace",
            ),
        ),
    ]