# Generated by Django 5.1.9 on 2025-08-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0005_prompt_workspace"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy single workspace field - use workspaces instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_prompts",
                to="workspaces.workspace",
            ),
        ),
        migrations.CreateModel(
            name="PromptWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        help_text="Prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_workspaces",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_prompts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_workspace",
                "unique_together": {("prompt", "workspace")},
            },
        ),
        migrations.AddField(
            model_name="prompt",
            name="workspaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="Workspaces this prompt belongs to",
                related_name="prompts",
                through="prompts.PromptWorkspace",
                to="workspaces.workspace",
            ),
        ),
    ]
