# Generated by Django 5.1.9 on 2025-08-04 08:53

from django.db import migrations


def migrate_single_to_multiple_workspaces(apps, schema_editor):
    """
    Migrate existing single workspace relationships to many-to-many relationships
    """
    Prompt = apps.get_model('prompts', 'Prompt')
    PromptWorkspace = apps.get_model('prompts', 'PromptWorkspace')
    
    # Get all prompts that have a single workspace assigned
    prompts_with_workspace = Prompt.objects.filter(workspace__isnull=False)
    
    print(f"Migrating {prompts_with_workspace.count()} prompts from single to multiple workspace relationships...")
    
    for prompt in prompts_with_workspace:
        # Create a PromptWorkspace relationship for the existing single workspace
        PromptWorkspace.objects.get_or_create(
            prompt=prompt,
            workspace=prompt.workspace
        )
        print(f"Migrated prompt '{prompt.name}' to workspace '{prompt.workspace.name}'")


def reverse_migrate_multiple_to_single_workspaces(apps, schema_editor):
    """
    Reverse migration: set the first workspace from many-to-many back to single workspace
    """
    Prompt = apps.get_model('prompts', 'Prompt')
    PromptWorkspace = apps.get_model('prompts', 'PromptWorkspace')
    
    for prompt in Prompt.objects.all():
        # Get the first workspace relationship (if any)
        first_workspace_rel = PromptWorkspace.objects.filter(prompt=prompt).first()
        if first_workspace_rel:
            prompt.workspace = first_workspace_rel.workspace
            prompt.save()
            print(f"Reverted prompt '{prompt.name}' to single workspace '{first_workspace_rel.workspace.name}'")


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0006_alter_prompt_workspace_promptworkspace_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_single_to_multiple_workspaces,
            reverse_migrate_multiple_to_single_workspaces
        ),
    ]
