# Generated by Django migration - add thinking_budget field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0007_auto_20250804_0853"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="thinking_budget",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Thinking budget for AI model (0 or positive integer). Controls deep thinking computation.",
                null=True,
            ),
        ),
    ]